### ISSUE TITLE
nlmsg error Operation not supported

### ISSUE THREAD

**Issue by smugcloud** [netoptimizer/prototype-kernel#19]
Hi @netoptimizer, thanks for putting this together; It's helping me learn XDP/BPF.

I am running through your slide deck on this repo, and after running `xdp_ddos01_blacklist`, I am getting `nlmsg error Operation not supported`.  Here is my environment, and full output.  Is this relying on a specific version of iproute2?

```
$ uname -a
Linux instance-3 4.11.0-041100-generic #201705041534 SMP Thu May 4 19:36:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsmod | grep virtio*
virtio_net             40960  0
virtio_scsi            20480  2
$ cat /boot/config-4.11.0-041100-generic | grep BPF*
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_MINIX_SUBPARTITION=y
CONFIG_X86_DIRECT_GBPAGES=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPQETHER=m
CONFIG_BT_HCIBPA10X=m
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_PARIDE_BPCK=m
CONFIG_SBP_TARGET=m
CONFIG_FIREWIRE_SBP2=m
CONFIG_SERIO_LIBPS2=y
CONFIG_USBPCWATCHDOG=m
CONFIG_DVB_LNBP21=m
CONFIG_DVB_LNBP22=m
CONFIG_USB_LEDS_TRIGGER_USBPORT=m
CONFIG_COMEDI_NI_LABPC_ISA=m
CONFIG_COMEDI_NI_LABPC_PCI=m
CONFIG_COMEDI_NI_LABPC_CS=m
CONFIG_COMEDI_NI_LABPC=m
CONFIG_COMEDI_NI_LABPC_ISADMA=m
CONFIG_ABP060MG=m
# CONFIG_RESET_TEGRA_BPMP is not set
CONFIG_BPF_EVENTS=y
CONFIG_TEST_BPF=m
$ ./xdp_ddos01_blacklist --dev ens4
Documentation:
 XDP: DDoS protection via IPv4 blacklist
This program loads the XDP eBPF program into the kernel.
Use the cmdline tool for add/removing source IPs to the blacklist
and read statistics.
 - Attached to device:ens4 (ifindex:2)
 - Export bpf-map:blacklist                      to   file:/sys/fs/bpf/ddos_blacklist
 - Export bpf-map:verdict_cnt                    to   file:/sys/fs/bpf/ddos_blacklist_stat_verdict
 - Export bpf-map:port_blacklist                 to   file:/sys/fs/bpf/ddos_port_blacklist
 - Export bpf-map:port_blacklist_drop_count_tcp  to   file:/sys/fs/bpf/ddos_port_blacklist_count_tcp
 - Export bpf-map:port_blacklist_drop_count_udp  to   file:/sys/fs/bpf/ddos_port_blacklist_count_udp
nlmsg error Operation not supported
link set xdp fd failed
$ ip -V
ip utility, iproute2-ss151103
```

**Comment by netoptimizer** [comment]
We should parse those netlink msg coming back from the kernel but afaik it
is first in kernel 4.12 that got the extack info.

Well, your issue is a setup issue with virtio_net driver... Look at the
kernel dmesg log at what it complains about...

What about playing with generic XDP on normal net devices?

**Comment by smugcloud** [comment]
That is an option, but your repo looked so inviting :)

I'll grab the latest kernel and try this out.  Any recommendations on kernel/tool versions, as well as generic programs to try?

**Comment by netoptimizer** [comment]
Hi @smugcloud 
I think you misunderstood me... you can still use my git-repo and tools for "[Generic XDP](https://prototype-kernel.readthedocs.io/en/latest/blogposts/xdp25_eval_generic_xdp_tx.html)". If a NIC-driver does NOT support XDP it will automatically fallback to using the "Generic XDP" (which will be slower, but allows you to play/code). Most of my tools allow you to force this mode via --skb-mode.

The ONLY point is that **virtio_net is difficult to setup**! ([Mailing list hint on setting up virtio](https://marc.info/?l=xdp-newbies&m=149486931113651&w=2))

For virtio_net the kernel dmesg log will show something like : 
> [...] can't set XDP while host is implementing LRO, disable LRO first

--Jesper

**Comment by smugcloud** [comment]
@netoptimizer Haha, I certainly did misunderstand :-).  Thank you for the continued tips.

My VM does have the virtio driver on my eth, so in order to experiment with XDP, is it best to apply the patches from your [Generic XDP](https://prototype-kernel.readthedocs.io/en/latest/blogposts/xdp25_eval_generic_xdp_tx.html) page? 

The log message you posted is exactly what I see.

**Comment by netoptimizer** [comment]
Hi @smugcloud 

Well, No, you don't need to apply any patches... but you do need to compile a very recent kernel (at minimum kernel tag v4.12-rc1).  I recommend git cloning and compiling the [net-next kernel](https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/). 

git clone git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git

So, after compiling and installing the net-next devel kerneI, will actually recommend installing the VM with another driver than virtio_net (if you don't care about performance), as this will cause it to use/fallback to the "Generic XDP" skb-based mode.  Else you can just used the --skbmode option in my tools.

This will allow you to play with writing some fun XDP examples and tools.  When you want performance you will need to buy a NIC which have [support for XDP in their driver](https://prototype-kernel.readthedocs.io/en/latest/networking/XDP/implementation/drivers.html).  Notice this is just a software limit, thus more and more drivers will support XDP.

**Comment by netoptimizer** [comment]
Notice: to reflect information "discovered" in this issue #19 thread

1. I updated the [blogpost](https://prototype-kernel.readthedocs.io/en/latest/blogposts/xdp25_eval_generic_xdp_tx.html) (commit 710d2ddaa36)

2. and I updated the [supported NIC drivers](https://prototype-kernel.readthedocs.io/en/latest/networking/XDP/implementation/drivers.html)

**Comment by smugcloud** [comment]
Thanks so much for this @netoptimizer.  Upgrading the Kernel to 4.12.0-rc4, and using skb-mode (I didn't feel like fighting virtio :-) ) resolves this issue, and I can run your examples.
