### ISSUE TITLE
Fail to compile 

### ISSUE THREAD

**Issue by cybernard** [netoptimizer/prototype-kernel#24]
ERROR: Need kernel source code to compile against
       and specifically tools/lib/bpf

In Opensuse
the kernel source is located /usr/src/linux 
linux is a symlink to another folder linux with the version # after it.

Your make file does NOT find it.

**Comment by netoptimizer** [comment]
If the kernel source is in a non-standard place, then you need to specify it in the command line when running *make*, like:

>  make kbuilddir=~/git/kernel/net-next/

This should be clear from the [Makefile](https://github.com/netoptimizer/prototype-kernel/blob/master/kernel/samples/bpf/Makefile#L65-L66) comment.

It is also documented here:
 https://prototype-kernel.readthedocs.io/en/latest/prototype-kernel/build-process.html
